### ISSUE TITLE
Missing background.js

### ISSUE THREAD

**Issue by RyWilliamson** [AaronV-T/imgur-Browsing-Aid#1]
When trying to load this as an unpacked extension this error is given the chrome://extensions window - Failed to load extension from: ~/Programming/imgur-Browsing-Aid
Could not load background script 'background.js'.

Edit: Should also mention this is on Chromium Version 47.0.2526.73 Built on Ubuntu 14.04, running on LinuxMint 17.3 (64-bit)

**Comment by AaronV-T** [comment]
I see. The extension is actually using a background.js, but I added it to gitignore because all it does is handle a small issue for users who installed < 0.4.0 and also sends a POST request to my website on install so that I can count installs. I assumed that it wouldn't be necessary for everyone else to copy it.

I see you've made a pull request and I will comment on it.

**Comment by AaronV-T** [comment]
Your pull requests has been pushed and the issue should no longer exist, thanks.
